# Generated by Django 4.1 on 2022-09-11 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concesionarios", "0002_auto_cliente_sucursal_delete_familiar"),
    ]

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50)),
                ("titulo_del_post", models.CharField(max_length=100)),
                ("auto", models.CharField(max_length=50)),
                ("posteo", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="sucursal",),
    ]
